name: Build and Publish image to ECR and update Infra Repo
on:
  push:
    branches:
    - master

# Only trigger the workflow if changes were made in the backend or frontend directories

    paths:
    - "backend/**"
    - "frontend/**"

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

# Login to Amazon ECR

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

# checkout code

    - name: checkout
      uses: actions/checkout@v4

# build and push images to ECR


# ЗАКОНЧИЛ НА ТОМ ЧТО ОСТАЛОСЬ ТОЛЬКО ЗАКИНУТЬ ВСЕ В ГИТ




    - name: build image
      run: |
        docker build ./backend/ -t ${{ secrets.ECR_REPO_BACKEND }}:${{ github.sha }}
        docker build ./frontend/ -t ${{ secrets.ECR_REPO_FRONTEND }}:${{ github.sha }}

        docker push ${{ secrets.ECR_REPO_FRONTEND }}:${{ github.sha }}
        docker push ${{ secrets.ECR_REPO_BACKEND }}:${{ github.sha }}

    - name: Checkout infra-repo and update tag
      run: |
        git clone https://x-access-token:${{ secrets.INFRA_REPO_TOKEN }}@github.com/wrQQng/Helm-iac.git
        cd appgit
        yq e '.backend.tag = "${{ github.sha }}"' -i helm-chart/values.yaml
        yq e '.frontend.tag = "${{ github.sha }}"' -i helm-chart/values.yaml
        git config user.email "CD@IlliaKhira.com"
        git config user.name "CD Bot"
        git add my-chart/values.yaml
        git commit -m "chore: update backend and frontend image tags to ${{ github.sha }}"
        git remote set-url origin https://x-access-token:${{ secrets.INFRA_REPO_TOKEN }}@github.com/wrQQng/Helm-iac.git
        git push
